### ISSUE TITLE
code style does not conform to PEP8 guidelines

### ISSUE THREAD

**Issue by abhishek-jaisingh** [basfom/EcoLab#20]
[pep8 guidelines](https://www.python.org/dev/peps/pep-0008/) should be followed to write clean and maintainable code. Should also have a **Style Guide** for the same

**Comment by abhishek-jaisingh** [comment]
made a PR #19 for the same, fixed style in socktest.py, can do the same for other files if its fine

**Comment by NemalPeiris** [comment]
@abhishekjiitr I would like to work on this issue if it is ok.

**Comment by abhishek-jaisingh** [comment]
@NemalPeiris, I already opened a PR for this an year ago, but this project seems to be inactive. Closing this now.

**Comment by bruno-chavez** [comment]
Just merged #21 sorry for not been focused on this project! If you want to keep contributing I'll test the PRs myself and provide feedback/merge accordingly.
